"""Add topics and complex question types

Revision ID: 73f523515ba5
Revises: 27f1dff6a48f
Create Date: 2026-07-27 10:07:08.874072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73f523515ba5'
down_revision: Union[str, Sequence[str], None] = '27f1dff6a48f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create Enums first
    questiontype = postgresql.ENUM('MULTIPLE_CHOICE', 'MATCHING', 'FILL_IN_BLANK', name='questiontype')
    questiontype.create(op.get_bind())
    difficultylevel = postgresql.ENUM('EASY', 'MEDIUM', 'HARD', name='difficultylevel')
    difficultylevel.create(op.get_bind())
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.add_column('exams', sa.Column('topic_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'exams_topic_id_fkey',
        'exams',
        'topics',
        ['topic_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.add_column('questions', sa.Column('topic_id', sa.UUID(), nullable=True))
    op.add_column('questions', sa.Column('question_type', sa.Enum('MULTIPLE_CHOICE', 'MATCHING', 'FILL_IN_BLANK', name='questiontype'), server_default='MULTIPLE_CHOICE', nullable=False))
    op.add_column('questions', sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'), server_default='MEDIUM', nullable=False))
    op.add_column('questions', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(
        'questions_topic_id_fkey',
        'questions',
        'topics',
        ['topic_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.add_column('submission_answers', sa.Column('answer_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('submission_answers', sa.Column('points_awarded', sa.Float(), nullable=True))
    op.drop_constraint(op.f('submission_answers_selected_option_id_fkey'), 'submission_answers', type_='foreignkey')
    op.drop_column('submission_answers', 'selected_option_id')
    op.alter_column('submissions', 'total_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'total_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.add_column('submission_answers', sa.Column('selected_option_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('submission_answers_selected_option_id_fkey'), 'submission_answers', 'options', ['selected_option_id'], ['id'], ondelete='CASCADE')
    op.drop_column('submission_answers', 'points_awarded')
    op.drop_column('submission_answers', 'answer_data')
    op.drop_constraint('questions_topic_id_fkey', 'questions', type_='foreignkey')
    op.drop_column('questions', 'metadata_json')
    op.drop_column('questions', 'difficulty')
    op.drop_column('questions', 'question_type')
    op.drop_column('questions', 'topic_id')
    op.drop_constraint('exams_topic_id_fkey', 'exams', type_='foreignkey')
    op.drop_column('exams', 'topic_id')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
    questiontype = postgresql.ENUM('MULTIPLE_CHOICE', 'MATCHING', 'FILL_IN_BLANK', name='questiontype')
    questiontype.drop(op.get_bind())
    difficultylevel = postgresql.ENUM('EASY', 'MEDIUM', 'HARD', name='difficultylevel')
    difficultylevel.drop(op.get_bind())
