"""topic_restructure

Revision ID: e598471b8b6d
Revises: 3205ff690df4
Create Date: 2026-07-31 12:14:57.234844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e598471b8b6d'
down_revision: Union[str, Sequence[str], None] = '3205ff690df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_briefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['study_materials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_briefs_id'), 'topic_briefs', ['id'], unique=False)
    op.add_column('flashcard_decks', sa.Column('material_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'flashcard_decks_material_id_fkey',
        'flashcard_decks',
        'study_materials',
        ['material_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.add_column('study_materials', sa.Column('topic_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'study_materials_topic_id_fkey',
        'study_materials',
        'topics',
        ['topic_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'study_materials_topic_id_fkey',
        'study_materials',
        type_='foreignkey',
    )
    op.drop_column('study_materials', 'topic_id')
    op.drop_constraint(
        'flashcard_decks_material_id_fkey',
        'flashcard_decks',
        type_='foreignkey',
    )
    op.drop_column('flashcard_decks', 'material_id')
    op.drop_index(op.f('ix_topic_briefs_id'), table_name='topic_briefs')
    op.drop_table('topic_briefs')
    # ### end Alembic commands ###
