import type { LucideIcon, LucideProps } from "lucide-react";
import {
  ArrowLeft,
  ArrowRight,
  Award,
  BarChart3,
  Bot,
  Check,
  CheckSquare,
  Circle,
  CircleAlert,
  CircleCheckBig,
  CircleDot,
  CircleHelp,
  CircleCheck,
  Clock,
  CloudUpload,
  Download,
  FileQuestion,
  FileText,
  FileSearch,
  Folder,
  Globe2,
  GraduationCap,
  House,
  IdCard,
  LayoutDashboard,
  ListFilter,
  LoaderCircle,
  LockKeyhole,
  LogOut,
  Medal,
  Menu,
  MoreVertical,
  Puzzle,
  Rocket,
  ScrollText,
  Search,
  Settings,
  Sparkles,
  Trash2,
  User,
  UserRoundCog,
  Users,
  TrendingDown,
  TrendingUp,
  Wrench,
  X,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  analytics: BarChart3,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  auto_awesome: Sparkles,
  auto_stories: GraduationCap,
  badge: IdCard,
  bar_chart: BarChart3,
  check: Check,
  check_box: CheckSquare,
  check_box_outline_blank: Circle,
  check_circle: CircleCheck,
  cloud_upload: CloudUpload,
  close: X,
  construction: Wrench,
  dashboard: LayoutDashboard,
  delete: Trash2,
  download: Download,
  error: CircleAlert,
  extension: Puzzle,
  filter_list: ListFilter,
  find_in_page: FileSearch,
  folder: Folder,
  folder_special: Folder,
  help: CircleHelp,
  help_outline: CircleHelp,
  history_edu: ScrollText,
  home: House,
  lock: LockKeyhole,
  logout: LogOut,
  manage_accounts: UserRoundCog,
  menu: Menu,
  military_tech: Medal,
  more_vert: MoreVertical,
  person: User,
  public: Globe2,
  quiz: FileQuestion,
  radio_button_checked: CircleDot,
  radio_button_unchecked: Circle,
  rocket: Rocket,
  schedule: Clock,
  school: GraduationCap,
  search: Search,
  settings: Settings,
  smart_toy: Bot,
  sync: LoaderCircle,
  task_alt: CircleCheckBig,
  description: FileText,
  group: Users,
  history: ScrollText,
  trending_down: TrendingDown,
  trending_up: TrendingUp,
  workspace_premium: Award,
};

interface AppIconProps extends Omit<LucideProps, "ref"> {
  name: string;
}

export function AppIcon({ name, ...props }: AppIconProps) {
  const Icon = icons[name];

  if (!Icon) {
    return null;
  }

  return <Icon aria-hidden="true" focusable="false" {...props} />;
}
